### PR TITLE
Lowering the devcert root CA expiration date.

### PR DESCRIPTION
**Pull request by smoak**
Previously, the root CA duration was set to 7000 days.
This lowers it down to 397 days.
On macOS, Chrome and Safari are giving errors regarding
the generated certificate.
Chrome shows "NET::ERR_CERT_VALIDITY_TOO_LONG"
Safari shows "certificate is not standards compliant"
This is because the requirements for root CAs
have changed particularly for macOS.

See https://support.apple.com/en-us/HT210176
Also see https://support.apple.com/en-us/HT211025

The recommended fix is to ensure it's issued maximum
validity of 397 days.

### CODE REVIEW

**Comment by dlannoye** [comment]
You will also need to run a build for the changes to be in /dist/certificates.js

**Comment by smoak** [comment]
> You will also need to run a build for the changes to be in /dist/certificates.js

Shouldn't that be handled in a build step rather than the PR? It's going to add a bunch of noise to the PR. I'd expect that to happen when the package gets packaged up and published.

**Comment by dlannoye** [comment]
I don't believe this fork has builds setup and the consumption is done via [github URL](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#github-urls) so it consumes it directly from github

**Comment by smoak** [comment]
Ran `npm run build` and committed the results

**Review by dlannoye — APPROVED** [review]

**Pull request merged**
